### ISSUE TITLE
How can one map backspace?

### ISSUE THREAD

**Issue by pelegm** [yzzyx/dwb#2]
I wish to have <kbd>Backspace</kbd> bringing me back (instead of the default <kbd>H</kbd>). How can this be done?

**Comment by yzzyx** [comment]
sorry for the very late reply - this is probably not the repository you're looking for.
The primary repo is located at http://bitbucket.org/portix/dwb and that repo contains a lot of updates that mine lacks (almost 3 years of development).

**Comment by pelegm** [comment]
Thanks :+1:
